apiVersion: v1
kind: Secret
metadata:
  name: aicodereviewer-secret
type: Opaque
data:
  DATABASE_URL: <paste_base64_here>
  GITHUB_CLIENT_ID: <paste_base64_here>
  GITHUB_CLIENT_SECRET: <paste_base64_here>
  GROQ_API_KEY: <paste_base64_here>
  BETTER_AUTH_SECRET: <paste_base64_here>
  BETTER_AUTH_URL: <paste_base64_here>